title: Francisco Correia Marques
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
description: A personal webpage
color_scheme: light
accent_color: pink
header:
  title: FMCM
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
    #- label: Projects
    #  url: /portfolio/
    #  style: link
    - label: Blog
      url: /blog/
      style: link
    # - label: Style Guide
    #   url: /style-guide/
    #   style: link
    - label: About
      url: /about/
      style: link
    # - label: Contact
    #   url: /contact/
    #   style: link
footer:
  content: >-
    Francisco Correia Marques 2020 <br>
    <small>Theme based on Exto</small>
  has_social: false
  social_links:
    - label: LinkedIn
      url: 'https://www.linkedin.com/in/franciscomcm'
      style: icon
      icon_class: fa-linkedin
      new_window: true
    # - label: GitLab
    #   url: 'https://gitlab.ethz.ch/fcorreia'
    #   style: icon
    #   icon_class: fa-gitlab
    #   new_window: true
    - label: GitHub
      url: 'https://github.com/franciscomcm'
      style: icon
      icon_class: fa-github
      new_window: true
    - label: Kaggle
      url: 'https://www.kaggle.com/franciscomcm'
      style: icon
      icon_class: fa-kaggle
      new_window: true 
    - label: Twitter
      url: 'https://twitter.com/_franciscomcm'
      style: icon
      icon_class: fa-twitter
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
