title: Francisco Correia Marques
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
description: A personal webpage
color_scheme: light
accent_color: pink
header:
  title: FMCM
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
    - label: Blog
      url: /blog/
      style: link
    - label: About
      url: /about/
      style: link

footer:
  content: >-
    Francisco Correia Marques 2020 <br>
    <small>Theme based on Exto</small>
  has_social: false
  social_links:
#    - label: ETH Zürich
  #    url: 'https://www.bone.ethz.ch/the-group/people/person-detail.MjUyMTcy.TGlzdC8xMzcyLC01MzUzOTg1MDM=.html'
  #    style: icon
  #    icon_class: fa-user-circle-o
  #    new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/in/franciscomcm'
      style: icon
      icon_class: fa-linkedin
      new_window: true
    - label: Google Scholar
      url: 'https://scholar.google.com/citations?hl=en&user=kd_6AzgAAAAJ'
      style: icon
      icon_class: fa-google
      new_window: true
    - label: ORCiD
      url: 'https://orcid.org/0000-0002-1651-0457'
      style: icon
      icon_class: fa-orcid
      new_window: true
    # - label: GitLab
    #   url: 'https://gitlab.ethz.ch/fcorreia'
    #   style: icon
    #   icon_class: fa-gitlab
      new_window: true
    - label: GitHub
      url: 'https://github.com/franciscomcm'
      style: icon
      icon_class: fa-github
      new_window: true
    - label: Kaggle
      url: 'https://www.kaggle.com/franciscomcm'
      style: icon
      icon_class: fa-kaggle
      new_window: true
    - label: Twitter
      url: 'https://twitter.com/_franciscomcm'
      style: icon
      icon_class: fa-twitter
      new_window: true

sass:
  indentWidth: 4
  style: nested
  precision: 10

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
